### ISSUE TITLE
Application not found

### ISSUE THREAD

**Issue by LemonIsAHe1** [YusufOzmen01/downgrid#1]
Was functioning perfectly the previous day and now when opening map links it says "C:\Users\Me\mapid-mapname.osz Application not found"
![image](https://user-images.githubusercontent.com/115420638/194770425-6f9ae923-f9fa-4a9f-9ffe-2d8882fa2391.png)

**Comment by YusufOzmen01** [comment]
Can you download a map through the website and double click to open it in game? It might fix stuff relating to the default app for the .osz file. Sorry for late response
